class TestData():
    BASE_URL = "https://www.casadellibro.com"
    SEARCH_TERM = " garcia"
    NAME = "Ina"
    SURNAME = "Istrati"
    EMAIL = "ina@example.com"
    PASSWORD = "1234Peeep"
    ADDRESS = "Madrid"
    POSTCODE = "50400"
    PHONE = "634348034"
    ERROR_MESSAGE = "Debes seleccionar un tipo de pago."